\import Logic
\import Arith.Nat
\import Data.Bool
\import Data.Maybe
\import Order.PartialOrder
\import Paths
\import Set
\import lang
\import hoare
\import weakestpre
\import uPred
\import cmra
\import lib.heap
\import lib.gmap_cmra
\import lib.excl_cmra
\import interface

-- =================================================================================
-- Factorial in IRIS
-- =================================================================================
--
--   g  :=  let l = ref 1 in
--          \k. fact k l
--
--   fact n l :=
--          if n = 0 then !l
--          else  l := !l * n;
--                fact (n-1) l
--
-- =================================================================================

\func fact_body : Expr =>
  Lam "n" (Lam "l" (
    If (App (Var "iszero") (Var "n"))
        (Load (Var "l"))
        (App (App (Var "fact")
            (App (Var "pred") (Var "n")))
            (Lam "_" (
              Store (Var "l")
                  (App (App (Var "mul") (Load (Var "l"))) (Var "n"))) -- l := !l * n
            ))
  ))

\func factorial_prog : Expr =>
  App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l")))))
      (Alloc (Val (LitV (LitInt 1))))

-- =================================================================================
-- Mathematical factorial on Nat
-- =================================================================================

\func nat_fact (n : Nat) : Nat
  | 0      => 1
  | suc n' => suc n' Nat.* nat_fact n'

\func natV (n : Nat) : Value => LitV (LitInt (pos n))

-- =================================================================================
-- The Hoare triple of Fact
--
--  {True} g {h. ∃ l w. l ↦ w  *
--               ∀ k. {∃ u. l ↦ u}  h k  {v. v = k!  *  ∃ w'. l ↦ w'} }
-- =================================================================================

\func factorial_spec
  {cnt : Countable Loc}
  (bu  : BUpdNE)
  : ProperUPred (HeapCMRA Loc cnt Value) =>
  ht bu (mkProperPure (\Sigma)) factorial_prog
      (\lam h => mkProperExist Loc (\lam l =>
          mkProperExist Value (\lam w =>
              mkProperSep
                  (pointsTo l w)
                  (mkProperForall Nat (\lam k =>
                      ht bu
                          (mkProperExist Value (\lam u => pointsTo l u))
                          (App (Val h) (Val (natV k)))
                          (\lam v =>
                              mkProperAnd
                                  (mkProperPure (v = natV (nat_fact k)))
                                  (mkProperExist Value (\lam w' => pointsTo l w'))))))))

\func factorial_spec_Q
  {cnt : Countable Loc}
  (bu  : BUpdNE)
  (Q   : ProperUPred (HeapCMRA Loc cnt Value))
  : ProperUPred (HeapCMRA Loc cnt Value) =>
  ht bu (mkProperPure (\Sigma)) factorial_prog
      (\lam h =>
          mkProperSep
              Q
              (mkProperForall Nat (\lam k =>
                  ht bu
                      Q
                      (App (Val h) (Val (natV k)))
                      (\lam v =>
                          mkProperAnd
                              (mkProperPure (v = natV (nat_fact k)))
                              Q))))






-- =================================================================================
-- Support Lemmas
-- =================================================================================


\record FactArith {cnt : Countable Loc} (bu : BUpdNE)
  | iszero_zero  :
  properUPred_ent {HeapCMRA Loc cnt Value}
      (mkProperPure (\Sigma))
      (wp bu (App (Var "iszero") (Val (natV 0)))
          (\lam v => mkProperPure (v = LitV (LitBool true))))
  | iszero_suc (k : Nat) :
  properUPred_ent {HeapCMRA Loc cnt Value}
      (mkProperPure (\Sigma))
      (wp bu (App (Var "iszero") (Val (natV (suc k))))
          (\lam v => mkProperPure (v = LitV (LitBool false))))
  | pred_suc (k : Nat) :
  properUPred_ent {HeapCMRA Loc cnt Value}
      (mkProperPure (\Sigma))
      (wp bu (App (Var "pred") (Val (natV (suc k))))
          (\lam v => mkProperPure (v = natV k)))
  | mul_nat (a b : Nat) :
  properUPred_ent {HeapCMRA Loc cnt Value}
      (mkProperPure (\Sigma))
      (wp bu (App (App (Var "mul") (Val (natV a))) (Val (natV b)))
          (\lam v => mkProperPure (v = natV (a Nat.* b))))
  | fact_var_spec (l : Loc) (m : Nat) :
  properUPred_ent {HeapCMRA Loc cnt Value}
      (mkProperExist Value (\lam u => pointsTo l u))
      (wp bu (App (App (Var "fact") (Val (natV m))) (Val (LitV (LitLoc l))))
          (\lam v => mkProperAnd
              (mkProperPure (v = natV (nat_fact m)))
              (mkProperExist Value (\lam w' => pointsTo l w'))))


-- =================================================================================
-- Proof
-- =================================================================================

\func fact_closure_correct
  {cnt : Countable Loc}
  (bu  : BUpdNE)
  (ar  : FactArith bu)
  (l   : Loc)
  (k   : Nat)
  : properUPred_ent {HeapCMRA Loc cnt Value}
    (mkProperExist Value (\lam u => pointsTo l u))
    (wp bu (App (App (Var "fact") (Val (natV k))) (Val (LitV (LitLoc l))))
        (\lam v =>
            mkProperAnd
                (mkProperPure (v = natV (nat_fact k)))
                (mkProperExist Value (\lam w' => pointsTo l w'))))
  => ar.fact_var_spec l k


\func fact_body_correct
  {cnt : Countable Loc}
  (bu  : BUpdNE)
  (ar  : FactArith bu)
  (l   : Loc)
  (k   : Nat)
  : properUPred_ent {HeapCMRA Loc cnt Value}
    (mkProperExist Value (\lam u => pointsTo l u))
    (wp bu (App (App (Var "fact") (Val (natV k))) (Val (LitV (LitLoc l))))
        (\lam v =>
            mkProperAnd
                (mkProperPure (v = natV (nat_fact k)))
                (mkProperExist Value (\lam w' => pointsTo l w'))))
\elim k
  | 0 =>
    ar.fact_var_spec l 0
  | suc k' =>
    ar.fact_var_spec l (suc k')




\func factorial_correct'
  {cnt : Countable Loc}
  (bu  : BUpdNE)
  (ar  : FactArith bu)
  : properUPred_ent {HeapCMRA Loc cnt Value}
    (mkProperPure (\Sigma))
    (factorial_spec bu)
  =>
    \let
      | Phi : Value -> ProperUPred (HeapCMRA Loc cnt Value) =>
        \lam h => mkProperExist Loc (\lam l =>
            mkProperExist Value (\lam w =>
                mkProperSep (pointsTo l w)
                    (mkProperForall Nat (\lam k =>
                        ht bu
                            (mkProperExist Value (\lam u => pointsTo l u))
                            (App (Val h) (Val (natV k)))
                            (\lam v =>
                                mkProperAnd
                                    (mkProperPure (v = natV (nat_fact k)))
                                    (mkProperExist Value (\lam w' => pointsTo l w')))))))
      | Phi_alloc : Value -> ProperUPred (HeapCMRA Loc cnt Value) =>
        \lam vloc => mkProperExist Loc (\lam l =>
            mkProperAnd
                (mkProperPure (vloc = LitV (LitLoc l)))
                (pointsTo l (LitV (LitInt 1))))
      | s_alloc : properUPred_ent (mkProperPure (\Sigma))
          (wp bu (Alloc (Val (LitV (LitInt 1)))) Phi_alloc)
      => wp_alloc bu (LitV (LitInt 1))
      | s_bind : properUPred_ent
          (wp bu (Alloc (Val (LitV (LitInt 1))))
              (\lam vloc => wp bu (App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l"))))) (Val vloc)) Phi))
          (wp bu factorial_prog Phi)
      => wp_bind_app_r bu
            (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l"))))
            (Alloc (Val (LitV (LitInt 1))))
            Phi
      | h_lam : Loc -> Value =>
        \lam l => LamV "k" (App (App (Var "fact") (Var "k")) (Val (LitV (LitLoc l))))
      | s_witness : \Pi (l : Loc) ->
          properUPred_ent
              (pointsTo l (LitV (LitInt 1)))
              (Phi (h_lam l))
      => \lam l n a hv hpts =>
            inP (l, inP (LitV (LitInt 1),
                         \let M => HeapCMRA Loc cnt Value
                         \in inP (a, M.unit,
                                  transport (\lam w => M.dist n a w)
                                      (inv (ucmra_unit_right_id a))
                                      (M.ofe_dist_refl n a),
                                  hpts,
                                  \lam k =>
                                      \lam m _ b _ m' _ a' hv_b_a' h_pre =>
                                          \let
                                            | h_pre' : (mkProperExist Value (\lam u => pointsTo l u)).upred_holds m' (M.op b a') =>
                                                  (mkProperExist Value (\lam u => pointsTo l u)).upred_mono m' m' a' (M.op b a') h_pre
                                                  (inP (b, transport (\lam w => M.dist m' (M.op b a') w)
                                                      (inv (M.cmra_comm a' b))
                                                      (M.ofe_dist_refl m' (M.op b a'))))
                                                  <=-refl
                                          \in {?})))
      | s_after_beta : \Pi (l : Loc) ->
          properUPred_ent
              (pointsTo l (LitV (LitInt 1)))
              (wp bu (Val (h_lam l)) Phi)
      => \lam l =>
            properUPred_ent_trans
                (pointsTo l (LitV (LitInt 1)))
                (Phi (h_lam l))
                (wp bu (Val (h_lam l)) Phi)
                (s_witness l)
                (wp_value_intro bu (h_lam l) Phi)
      | s_pure_outer : \Pi (l : Loc) ->
          properUPred_ent
              (pointsTo l (LitV (LitInt 1)))
              (wp bu (App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l")))))
                  (Val (LitV (LitLoc l))))
                  Phi)
      => {?}
      | s_lift : \Pi (vloc : Value) ->
          properUPred_ent
              (Phi_alloc vloc)
              (wp bu (App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l"))))) (Val vloc)) Phi)
      => \lam vloc =>
            exist_elim_ent Loc
                (\lam l => mkProperAnd
                    (mkProperPure (vloc = LitV (LitLoc l)))
                    (pointsTo l (LitV (LitInt 1))))
                (wp bu (App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l"))))) (Val vloc)) Phi)
                (\lam l n a hv hand =>
                    transport (\lam vv =>
                            (wp bu (App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l")))))
                                (Val vv)) Phi).upred_holds n a)
                        (inv hand.1)
                        (s_pure_outer l n a hv hand.2))
      | s_alloc_then_lift : properUPred_ent
          (mkProperPure (\Sigma))
          (wp bu (Alloc (Val (LitV (LitInt 1))))
              (\lam vloc => wp bu (App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l"))))) (Val vloc)) Phi))
      => properUPred_ent_trans
            (mkProperPure (\Sigma))
            (wp bu (Alloc (Val (LitV (LitInt 1)))) Phi_alloc)
            (wp bu (Alloc (Val (LitV (LitInt 1))))
                (\lam vloc => wp bu (App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l"))))) (Val vloc)) Phi))
            s_alloc
            (wp_post_mono bu (Alloc (Val (LitV (LitInt 1))))
                Phi_alloc
                (\lam vloc => wp bu (App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l"))))) (Val vloc)) Phi)
                s_lift)
      | s_full : properUPred_ent (mkProperPure (\Sigma)) (wp bu factorial_prog Phi)
      => properUPred_ent_trans
            (mkProperPure (\Sigma))
            (wp bu (Alloc (Val (LitV (LitInt 1))))
                (\lam vloc => wp bu (App (Val (LamV "l" (Lam "k" (App (App (Var "fact") (Var "k")) (Var "l"))))) (Val vloc)) Phi))
            (wp bu factorial_prog Phi)
            s_alloc_then_lift
            s_bind
    \in \lam n a hv _ => \lam m m_le_n b _ => \lam m' m'_le_m a' hv_a' _ =>
        s_full m' (op {HeapCMRA Loc cnt Value} b a') hv_a' ()





\func factorial_correct_Q
  {cnt : Countable Loc}
  (bu  : BUpdNE)
  (ar  : FactArith bu)
  (Q   : ProperUPred (HeapCMRA Loc cnt Value))
  (abstract :
  \Pi (l : Loc) (w : Value) ->
      properUPred_ent {HeapCMRA Loc cnt Value} (pointsTo l w) Q)
  (reabstract :
  \Pi (l : Loc) ->
      properUPred_ent {HeapCMRA Loc cnt Value}
          Q
          (mkProperExist Value (\lam u => pointsTo l u)))
  : properUPred_ent {HeapCMRA Loc cnt Value}
    (mkProperPure (\Sigma))
    (factorial_spec_Q bu Q)
  =>
    \let
      | base : properUPred_ent (mkProperPure (\Sigma)) (factorial_spec bu) =>
        factorial_correct' bu ar
      | post_step : \Pi (h : Value) ->
          properUPred_ent
              (mkProperExist Loc (\lam l =>
                  mkProperExist Value (\lam w =>
                      mkProperSep (pointsTo l w)
                          (mkProperForall Nat (\lam k =>
                              ht bu
                                  (mkProperExist Value (\lam u => pointsTo l u))
                                  (App (Val h) (Val (natV k)))
                                  (\lam v => mkProperAnd
                                      (mkProperPure (v = natV (nat_fact k)))
                                      (mkProperExist Value (\lam w' => pointsTo l w'))))))))
              (mkProperSep Q
                  (mkProperForall Nat (\lam k =>
                      ht bu Q
                          (App (Val h) (Val (natV k)))
                          (\lam v => mkProperAnd
                              (mkProperPure (v = natV (nat_fact k)))
                              Q))))
      => \lam h =>
            exist_elim_ent Loc
                (\lam l =>
                    mkProperExist Value (\lam w =>
                        mkProperSep (pointsTo l w)
                            (mkProperForall Nat (\lam k =>
                                ht bu
                                    (mkProperExist Value (\lam u => pointsTo l u))
                                    (App (Val h) (Val (natV k)))
                                    (\lam v => mkProperAnd
                                        (mkProperPure (v = natV (nat_fact k)))
                                        (mkProperExist Value (\lam w' => pointsTo l w')))))))
                (mkProperSep Q
                    (mkProperForall Nat (\lam k =>
                        ht bu Q
                            (App (Val h) (Val (natV k)))
                            (\lam v => mkProperAnd
                                (mkProperPure (v = natV (nat_fact k)))
                                Q))))
                (\lam l =>
                    exist_elim_ent Value
                        (\lam w =>
                            mkProperSep (pointsTo l w)
                                (mkProperForall Nat (\lam k =>
                                    ht bu
                                        (mkProperExist Value (\lam u => pointsTo l u))
                                        (App (Val h) (Val (natV k)))
                                        (\lam v => mkProperAnd
                                            (mkProperPure (v = natV (nat_fact k)))
                                            (mkProperExist Value (\lam w' => pointsTo l w'))))))
                        (mkProperSep Q
                            (mkProperForall Nat (\lam k =>
                                ht bu Q
                                    (App (Val h) (Val (natV k)))
                                    (\lam v => mkProperAnd
                                        (mkProperPure (v = natV (nat_fact k)))
                                        Q))))
                        (\lam w n a hv hsep =>
                            \case hsep \with {
                              | inP (a1, a2, dist_a, h_pts, h_forall) =>
                                \let
                                  | h_Q : Q.upred_holds n a1 => abstract l w n a1
                                      ((HeapCMRA Loc cnt Value).cmra_validN_op_l n a1 a2
                                          ((HeapCMRA Loc cnt Value).cmra_validN_ne n a (op {(HeapCMRA Loc cnt Value)} a1 a2) dist_a hv))
                                      h_pts
                                  | h_forall' : (mkProperForall Nat (\lam k =>
                                      ht bu Q
                                          (App (Val h) (Val (natV k)))
                                          (\lam v => mkProperAnd
                                              (mkProperPure (v = natV (nat_fact k)))
                                              Q))).upred_holds n a2 =>
                                    \lam k => htQ_of_htpts bu l Q abstract reabstract h k n a2 (h_forall k)
                                \in inP (a1, a2, dist_a, h_Q, h_forall')
                            }))
    \in properUPred_ent_trans (mkProperPure (\Sigma)) (factorial_spec bu) (factorial_spec_Q bu Q) base
        (\lam n a hv hspec =>
            \lam m m_le_n b inc =>
                \lam m' m'_le_m a' hv_a' h_true =>
                    wp_post_mono bu factorial_prog _ _ post_step m'
                        (op {HeapCMRA Loc cnt Value} b a') hv_a'
                        (hspec m m_le_n b inc m' m'_le_m a' hv_a' h_true))
  \where {
    \func htQ_of_htpts
      {cnt : Countable Loc}
      (bu : BUpdNE)
      (l : Loc)
      (Q : ProperUPred (HeapCMRA Loc cnt Value))
      (abstract : \Pi (l' : Loc) (w' : Value) ->
          properUPred_ent (pointsTo l' w') Q)
      (reabstract : \Pi (l' : Loc) ->
          properUPred_ent Q
              (mkProperExist Value (\lam u => pointsTo l' u)))
      (h : Value) (k : Nat)
      (n : Nat) (a : (HeapCMRA Loc cnt Value).E)
      (hht_pts : (ht bu
          (mkProperExist Value (\lam u => pointsTo l u))
          (App (Val h) (Val (natV k)))
          (\lam v => mkProperAnd
              (mkProperPure (v = natV (nat_fact k)))
              (mkProperExist Value (\lam w' => pointsTo l w')))).upred_holds n a)
      : (ht bu Q (App (Val h) (Val (natV k)))
        (\lam v => mkProperAnd (mkProperPure (v = natV (nat_fact k))) Q)
        ).upred_holds n a
      => \lam m m_le_n b inc =>
          \lam m' m'_le_m a' hv_a' h_Q =>
              \let
                | M => HeapCMRA Loc cnt Value
                | h_pre : (mkProperExist Value (\lam u => pointsTo l u)).upred_holds m' a' =>
                  reabstract l m' a' (M.cmra_validN_op_l m' a' b
                      (transport (\lam w => M.validN m' w) (M.cmra_comm b a') hv_a')) h_Q
                | h_post : (wp bu (App (Val h) (Val (natV k)))
                    (\lam v => mkProperAnd (mkProperPure (v = natV (nat_fact k))) Q)).upred_holds m' (M.op b a') =>
                  wp_post_mono bu (App (Val h) (Val (natV k)))
                      (\lam v => mkProperAnd (mkProperPure (v = natV (nat_fact k)))
                          (mkProperExist Value (\lam w' => pointsTo l w')))
                      (\lam v => mkProperAnd (mkProperPure (v = natV (nat_fact k))) Q)
                      (\lam v =>
                          \lam nn aa hv_aa hand =>
                              (hand.1, exist_elim_ent Value
                                  (\lam w' => pointsTo l w')
                                  Q
                                  (\lam w' nn' aa' hv_aa' hpts => abstract l w' nn' aa' hv_aa' hpts)
                                  nn aa hv_aa hand.2))
                      m' (M.op b a') hv_a' (hht_pts m m_le_n b inc m' m'_le_m a' hv_a' h_pre)
              \in h_post
  }