\import interface
\import lang
\import uPred
\import cmra
\import weakestpre
\import lib.heap
\import lib.gmap_cmra
\import lib.excl_cmra

-- =================================================================================
-- Hoare triples
-- =================================================================================

\func ht
  {cnt : Countable Loc}
  (bu  : BUpdNE)
  (P   : ProperUPred (HeapCMRA Loc cnt Value))
  (e   : Expr)
  (Phi : Value -> ProperUPred (HeapCMRA Loc cnt Value))
  : ProperUPred (HeapCMRA Loc cnt Value)
  => mkProperPersistently (mkProperWand P (wp bu e Phi))