\import interface
\import lang
\import Paths
\import uPred
\import cmra
\import weakestpre_old
\import lib.heap
\import lib.gmap_cmra
\import lib.excl_cmra

-- =================================================================================
-- Historical fixed-HeapCMRA Hoare triples.
-- =================================================================================

\func ht
  {cnt : Countable Loc}
  (P   : ProperUPred (HeapCMRA Loc cnt Value))
  (e   : Expr)
  (Phi : Value -> ProperUPred (HeapCMRA Loc cnt Value))
  : ProperUPred (HeapCMRA Loc cnt Value)
  => mkProperPersistently (mkProperWand P (wp e Phi))


-- =================================================================================
-- Hoare-triple rules
-- =================================================================================


\lemma ht_conseq
  {cnt : Countable Loc}
  (P P' : ProperUPred (HeapCMRA Loc cnt Value))
  (e    : Expr)
  (Phi Phi' : Value -> ProperUPred (HeapCMRA Loc cnt Value))
  (hP   : properUPred_ent P' P)
  (hPhi : \Pi (v : Value) -> properUPred_ent (Phi v) (Phi' v))
  : properUPred_ent (ht P e Phi) (ht P' e Phi')
  =>
    \let M => HeapCMRA Loc cnt Value
    \in \lam n a hv h_pers =>
        \lam k k_le_n a' hv_core_a' hP'_a' =>
          \let
            | hv_a' : M.validN k a' =>
                cmra_validN_op_r {M} k (ucmra_core {M} a) a' hv_core_a'
            | hP_a' : P.upred_holds k a' => hP k a' hv_a' hP'_a'
            | h_wp_core_a' : (wp e Phi).upred_holds k
                (M.op (ucmra_core {M} a) a') =>
                h_pers k k_le_n a' hv_core_a' hP_a'
          \in wp_post_mono e Phi Phi' hPhi k
              (M.op (ucmra_core {M} a) a') hv_core_a' h_wp_core_a'
